### ISSUE TITLE
Charaterize the chromatic seeing with U-MAP

### ISSUE THREAD

**Issue by ztq1996** [LSSTDESC/SprintWeek2024#17]
# Charaterize the chromatic seeing with U-MAP

A recent study in the photo-z field shows that [U-MAP](https://umap-learn.readthedocs.io/en/latest/) is better at forming a continuous latent space for the color-redshift relation, compared to the commonly used self-organizing map. 
Continuity is important for tasks involving interpolation, which, is critical when the training sample is sparse and unrepresentative. 

We would like to explore whether we can characterize the color-chromatic_seeing relation with U-MAP, as a previous study done by Jonathan Calixto, Pat Burchat (@burchat), Sid Mau (@sidneymau ), and Shuang Liang (@shuang92) shows that SOM can map the color-chromatic_seeing relation but are pretty discontinuous. U-MAP could potentially solve this issue and we would like to explore this. 

Contacts: TQ, Shuang
Day/Time: all week
Main communication channel: 
GitHub repo: 
Zoom room (if applicable): 

Run UMAP on the catalog pulled for the SOM and make some comparison

## Resources and skills needed

Interested (or just curiosity) in chromatic PSF stuff 

## Detailed description

TBD

**Comment by arunkannawadi** [comment]
Project to be announced.
