### ISSUE TITLE
Logistics for photo-Z data challenge.

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/SprintWeek2024#23]
# Logistics for photo-Z data challenge.

Figuring out how to build on work by Yash, Eric, Sid, TQ, Shuang & others to set up a photo-Z data challenge.

Contacts:
Day/Time: ??
Main communication channel:  semaphore flags & good vibes
GitHub repo: https://github.com/LSSTDESC/rail_pipelines
Zoom room (if applicable):

## Goals and deliverable

We would like to set up the "meta" project files that we will can use a starting points for the photo-Z data and get a core group of people able to contribute.

## Resources and skills needed

Enthusiasm

**Comment by arunkannawadi** [comment]
Timescale for this challenge is within ~1 year.
