### ISSUE TITLE
Avoid warnings when running metadetect unit tests

### ISSUE THREAD

**Issue by arunkannawadi** [LSSTDESC/SprintWeek2024#4]
# Avoid warnings when running metadetect unit tests

Take action to avoid the division by zero warning and DeprecationWarning when running LSST-specific unit tests

Contacts: @arunkannawadi 
Day/Time: Monday 10-12 PDT
Main communication channel: #desc-sprint-fall24-metadetect
GitHub repo: https://github.com/esheldon/metadetect (Forking required)
Zoom room (if applicable): DESC #5

## Goals and deliverable

The unit tests should run without any warning

## Resources and skills needed

Very minimal Python knowledge. No knowledge of weak lensing shear estimation needed.

## Detailed description

See https://github.com/esheldon/metadetect/actions/runs/10257974332/job/28380017308#step:6:844 for the logs of the warnings.

**Comment by arunkannawadi** [comment]
@beckermr we're trying to dig into some ancient history now if you want to join us.

**Comment by beckermr** [comment]
I am in a meeting right now sorry. I left a comment on ismael's PR.

**Comment by arunkannawadi** [comment]
Done in https://github.com/esheldon/metadetect/pull/224
