### ISSUE TITLE
OpenCosmo Soft Launch and Feedback Session

### ISSUE THREAD

**Issue by AstroPatty** [LSSTDESC/SprintWeek2024#5]
Participants in this session will have the opportunity to test and provide feedback on the new OpenCosmo HACC Compute Portal, which is designed to provide easy access to and basic analysis tools for large cosmological simulations. 

Contacts: Patrick Wells, Patricia Larsen, Michael Buehlmann (Contact: LSST Slack)
Day/Time: Wednesday, 1PM
Main communication channel: #desc-sprint-feb2024-argonne-sims (will be renamed)
GitHub repo: TBD
Zoom room (if applicable): TBD

## Goals and deliverable

The primary goal of this sprint is to collect feedback on the current state of the HACC Compute Portal (see below for description) and potential directions for improvement. Users will have the opportunity to test the portal on their personal machines and provide feedback directly to the development team in attendance and in writing. Potential areas of feedback include:

- User interface (clarity, ease of use, etc.)
- Available analysis routines (and analyses that could be useful but are not implemented)
- Data sets and data types (specific simulations and/or data products)

The deliverable will be the compiled feedback of the participants, which will be used to guide our development going forward.

## Resources and skills needed

A computer
A Globus account
A willingness to provide feedback

## Detailed description

OpenCosmo is a cross-lab effort to make cutting-edge datasets accessible to the entire astronomy community. The goal is to enable easy querying and analysis of these datasets without having to move them over the internet.

The HACC Compute Portal is a tool for accessing and performing simple analyses on cosmological simulations produced by the Hardware/Hybrid Accelerated Cosmology Code (HACC) team at Argonne National Laboratory. These simulations represent some of the largest cosmological simulations ever produced, with total data volumes in the petabyte range. This includes the OuterRim simulation, which forms the basis of the CosmoDC2 synthetic galaxy catalog. The HACC Compute Portal allows astrophysicists to query these datasets quickly and reliably through an intuitive and easy-to-use user interface which will eventually be made publicly available.

The compute portal is not yet public, and feedback from people outside the development team is critical to building a tool that is useful to the community. Attendees while have the opportunity to access the new OpenCosmo compute portal and run queries on our datasets. Participants will have opportunity to provide feedback both directly to the development in attendance and in writing

**Comment by arunkannawadi** [comment]
Feedback is still welcome. Access will continue to exist for the near future now.
