### ISSUE TITLE
AnaCal for Clusters

### ISSUE THREAD

**Issue by zhouconghao** [LSSTDESC/SprintWeek2024#7]
AnaCal for Clusters

We develop utilities and benchmark the performance of Analytic Calibration for Perturbation Estimation from Galaxy Images [AnaCal](https://github.com/mr-superonion/AnaCal) in this session. 

Contacts: Conghao Zhou, XIangchong Li
Day/Time: MTWThF 
Main communication channel: #desc-cl-shear-icl
GitHub repo: [xlens](https://github.com/mr-superonion/xlens)
Zoom room (if applicable):

## Goals and deliverable

We aim to have a first set of statistics of shear biases for clusters of different masses under different noise realization. 

## Resources and skills needed

DM pipeline and shear calibration. 

## Detailed description

Accurate recovery of the lensing signal is critical to extracting cosmology information from galaxy clusters. However, the typical scene for shear estimation in cluster fields differs from that for 3x2pt analyses. In this project, we will build new and extend existing infrastructures to validate one of the two fiducial DESC shear estimation schemes: AnaCal, for the high-shear regime in the cluster field. The simulations and analysis software from this project will enable more realistic and robust simulations for further studies in cluster shear estimation.

**Comment by arunkannawadi** [comment]
Thanks for specifying the zoom link but for the sprint week, we will use one of the links listed on the [Confluence page](https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=501776744). Depending on the physical room at SLAC, you'll need to pick one appropriate. Also, make sure you're not posting the password embedded links publicly here (I removed the password embedded link from the description).

**Comment by zhouconghao** [comment]
Thanks @arunkannawadi !
