### ISSUE TITLE
[Tutorial] Tutorial for AnaCal Shear Estimator

### ISSUE THREAD

**Issue by mr-superonion** [LSSTDESC/SprintWeek2024#9]
**What is the main topic of this tutorial**: [AnaCal](https://github.com/mr-superonion/AnaCal), python, shear estimation, cluster lensing

**One line description**
Teach how to use AnaCal to detect galaxies, measure shear and apply it to cluster analysis.

**Learning goals**

- goal 1: Learn to install AnaCal from conda-forge or pypi (@mr-superonion );
- goal 2: Learn to use AnaCal to detect galaxies and measure shear (@mr-superonion );
- goal 3: Learn to use the shear catalog for cluster analysis (@zhouconghao)

**Comment by arunkannawadi** [comment]
We have tutorials planned for the whole day Monday and Tuesday. Any chance this could be done on Wednesday instead?

**Comment by ztq1996** [comment]
Hi @arunkannawadi  - I think the audience for this session is fully separable from the supernova session, maybe these two can go parallel?

**Comment by arunkannawadi** [comment]
Fine with me. I thought the reason why we moved away from having parallel tutorials in the first place is that people shouldn't feel like they should choose one over the other.

**Comment by ztq1996** [comment]
Yeah I still stand by that, but this came up late and I also don't want to make the anacal people wait till Wednesday...
